### ISSUE TITLE
[Functions] Do not run func extensions install when using extension bundles

### ISSUE THREAD

**Issue by pragnagopa** [microsoft/azure-maven-plugins#609]
### Plugin name and version
Functions

Related archetype update: https://github.com/Microsoft/azure-maven-archetypes/issues/108

If an app is using bundles,  do not run `func extensions install` . This will eliminate the requirement for dotnet core / func cli at the app creation time.

cc: @soninaren @jeffhollan  @mattchenderson 

@jdneo / @Flanker32  - Please let us know if you have any questions.

**Comment by Flanker32** [comment]
@pragnagopa  Sorry for reply late, so the maven plugin should detect whether the project using bundles and decide whether to execute `func extensions install`? Is there any schema here, or we just need to check `extensionBundle` exist in host.json?

**Comment by pragnagopa** [comment]
> Is there any schema here, or we just need to check extensionBundle exist in host.json?

Yes you need to check host.json if the app is using extension bundle.

@soninaren - Can you please paste a sample host.json?

**Comment by pragnagopa** [comment]
@soninaren will be updating CLI to take care of this scenario. Please hold off on this item until we have new CLI.

**Comment by pragnagopa** [comment]
cc @amamounelsayed

@Flanker32  - Can you please verify if this issue is already addressed?

**Comment by Flanker32** [comment]
@pragnagopa We are not aware of the status of extension bundles and function core tools and this issue is still in backlog. 

Besides, does this issue depends on https://github.com/microsoft/azure-maven-plugins/issues/658?

**Comment by pragnagopa** [comment]
@Flanker32 - this is unrelated to issue #658 

if an app is using extension bundles, mvn plugin should not run function extensions install explicitly. @soninaren - Are we still waiting on CLI updates?

**Comment by soninaren** [comment]
@pragnagopa The CLI updates required for this use are complete.

Here is the sample host.json file. You need to only check for the id property since the version can change.
```JSON
{
    "version": "2.0",
    "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[1.*, 2.0.0)"
    }
}
```

**Comment by daniel-rocha** [comment]
Is there any way for me to test this change?

**Comment by soninaren** [comment]
@daniel-rocha This is an optimization to make sure we don't call `func extensions install` where we don't need. To test this change, Once the plugin has been updated execute the `run`  command and check if the maven plugin is calling `func extensions install`

**Comment by daniel-rocha** [comment]
@soninaren right. is there an internal repo where a new version of the plugin is updated?

**Comment by Flanker32** [comment]
@soninaren Before release to production, we will release it to staging repo first for test purpose, i'll share the access once it is done.

**Comment by Flanker32** [comment]
@pragnagopa  Fixed in #771, besides, could you please share us the oldest func cli version which support function bundle? So that we could still work in local if user didn't update their function cli.

**Comment by soninaren** [comment]
Oldest CLI version that supported bundles is `2.6.666` in case you still need it.

**Comment by Flanker32** [comment]
> Oldest CLI version that supported bundles is `2.6.666` in case you still need it.

@soninaren Thanks for the information, i wonder whether we should show an info when user install the cli with lower version, for they may not be able to run it locally.

**Comment by pragnagopa** [comment]
@Flanker32  - Is this issue addressed? Can it be closed?

**Comment by Flanker32** [comment]
@pragnagopa This has been done in #771, but the pr of archetype is pending for @mattchenderson said a few other bundles dependencies will come together. Is this job done? So that we could merge the archetype [pr](https://github.com/microsoft/azure-maven-archetypes/pull/109) and close this issue.

**Comment by Flanker32** [comment]
@pragnagopa This has been released with azure functions maven plugin 1.3.4, so close it.
